// src/app/app.component.ts
import { HttpClient } from '@angular/common/http';
import { Component, OnInit } from '@angular/core';

import User from '../models/User';

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.css'],
})
export class AppComponent implements OnInit {
  title = 'simple-ng';
  users: User[] = [];

  // private API_URL = 'https://63998da716b0fdad77409a5e.mockapi.io/api/v1/hikers';
  private API_URL = '/assets/users.json';

  constructor(private http: HttpClient) {}

  getUsers() {
    this.http
      .get<User[]>(this.API_URL, { responseType: 'json' })
      .subscribe((data: User[]) => {
        this.users = data;
      });
  }

  // create a constructor to get http client

  ngOnInit() {
    this.getUsers();
  }
  async confirmDelete() {
    confirm('Are you sure you want to delete this user?');
  }

  async deleteUser(id: string) {
    await this.confirmDelete();
    this.users = this.users.filter((user) => user.id !== id);
  }

  convertDate(date: string) {
    return new Date(date).toLocaleDateString(undefined, {
      day: '2-digit',
      month: '2-digit',
      year: 'numeric',
    });
  }

  getBreakpoint() {
    return window
      .getComputedStyle(document.body, ':before')
      .content.replace(/\"/g, '');
  }

  isMobile() {
    console.log(this.getBreakpoint());
    return this.getBreakpoint() === 'mobile';
  }
  isPc() {
    return this.getBreakpoint() === 'pc';
  }
}

<div class="root">
  <div class="header">
    <img style="width: 250px; height: 86px;" src="/assets/Logo-SDWorx.png" />
    <!-- iff breakpoint hover 500; hide img -->

    <img class="second-logo" style="width: 150px;" src="/assets/sd-worx-symbool.png" />
  </div>
  <br />
  <div class="paper computer">
    <h2>Attendees ({{users.length}})</h2>
    <div class="table">
      <table>
        <thead>
          <tr>
            <th></th>
            <th></th>
            <th>Name</th>
            <th>Date Of Birth</th>
            <th>City</th>
            <th>Country</th>
            <th></th>
          </tr>
        </thead>
        <tbody>
          <tr *ngFor="let user of users; index as i">
            <td class="index">#{{i+1}}</td>
            <td><img class="avatar" src={{user.avatar}} /></td>
            <td>{{user.name}}</td>
            <td>{{convertDate(user.dateOfBirth)}}</td>
            <td>{{user.city}}</td>
            <td>{{user.country}}</td>
            <td><button (click)="deleteUser(user.id)"><img src="/assets/bin.svg"></button></td>
          </tr>
        </tbody>
      </table>
    </div>
  </div>
  <div class="paper mobile grid">
    <div class="item">
      <span class="title  ">Attendees ({{users.length}})</span>
    </div>
    <div class="item" *ngFor="let user of users">
      {{user.name}}
    </div>
  </div>
</div>

// src/App.jsx
import React, { useEffect, useReducer, useState } from "react"
import './App.css';
import Logo from "./assets/logo";
import TrahsBin from "./assets/trahsBin";
import Decor from "./assets/decor.png"
import Avatar from "./assets/Avatar.png"
import axios from "axios";
import { initialState, reducer } from "./reducer/reducer";
import moment from "moment/moment";

function App() {

  const [data, setData] = useState([])

  useEffect(() => {
    axios.get("https://63998da716b0fdad77409a5e.mockapi.io/api/v1/hikers").then(res => {
      console.log(res)
      setData(res.data)
      dispatch({ type: "ADD", payload: res.data })
    }).catch(err => console.log(err))
  }, [])

  const [state, dispatch] = useReducer(reducer, initialState)

  const deleteHiker = (id) => {
    var bool = window.confirm("Are you sure to delete this row?")
    bool && dispatch({ type: "DELETE", payload: id })
  }

  return (
    <div className="App">
      <div className="navbar d-flex justify-between align-center">
        <Logo />
        <img className="decor" src={Decor} alt="..." />
      </div>
      <div className="wrapper">
        <h2 className="heading">Attendees <span>{data.length}</span></h2>
        <table cellPadding={0} cellSpacing={0} >
          <thead>
            <tr>
              <th>0</th>
              <th>Name</th>
              <th>Date of birth</th>
              <th>City</th>
              <th>Country</th>
              <th>0</th>
            </tr>
          </thead>
          <tbody>
            {
              state.hikers?.length != 0 && state.hikers.map((item, index) => (
                <tr key={index}>
                  <td className="index">
                    #{item.id}
                  </td>
                  <td className="avatarBox"><img src={item.avatar} alt="..." className="avatar" /></td>
                  <td className="nameBox"><p className="name">{item.name}</p> <p className="d-none mobile-place"> {item.city}</p></td>
                  <td>{moment(item.dateOfBirth).format('L')}</td>
                  <td className="place">{item.city}</td>
                  <td onClick={() => deleteHiker(item.id)} className="pointer"><TrahsBin /></td>
                </tr>
              ))
            }
          </tbody>
        </table>
      </div>
    </div>
  );
}

export default App;
